# next-app Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
  labels:
    app: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
        - name: next-app
          image: modesage/todo-app-argo:e7824848644777a73d20cf7dc381304c5dd7f8e0
          ports:
            - containerPort: 3000

---
# next-app Service
apiVersion: v1
kind: Service
metadata:
  name: next-app-svc
spec:
  selector:
    app: next-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
